version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard_serverclient
    restart: unless-stopped
    networks:
      - backbone
    ports:
      - 80:80
      - 8000:8000
      - 9000:9000
      - 9001:9001
      - 27500:27500
      - 28910:28910
      - 29900:29900
      - 29901:29901
      - 29920:29920
      - 27900:27900/udp
      - 27901:27901/udp
    volumes:
      - './wireguard:/config'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  nginx:
    depends_on:
      - wireguard
    build: ./dwc_nginx
    container_name: dwc_nginx
    network_mode: service:wireguard
    restart: unless-stopped
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro

  dwc:
    depends_on:
      - wireguard
    build: ./dwc_server
    container_name: dwc_server
    network_mode: service:wireguard
    restart: unless-stopped
    volumes:
      - data:/dwc/data

networks:
  backbone:
    driver: bridge

volumes:
  data: